spring:
  datasource:
    url: jdbc:oracle:${DB_PROD_SERVER:thin:@oracle.fiap.com.br}:${DB_PROD_PORT:1521}:${DB_PROD_NAME:ORCL}?createDatabaseIfNotExist=true
    username: ${DB_PROD_USERNAME:RM550806}
    password: ${DB_PROD_PASSWORD:260205}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true